### ISSUE TITLE
Not an issue just wanted to say hello

### ISSUE THREAD

**Issue by laurinyev** [TheNameOfAnAmatuer/CR-OS#1]
Hello Core,do you remember me?

the h0r.net trailer just droped, here it is:https://www.youtube.com/watch?v=qO1ftzaAsv8
it is edited by me,I want this to get a little attention, can you advertize it a bit?

thank you if you can.

lolguy91, the asm guy

**Comment by TheNameOfAnAmatuer** [comment]
Yes I do remember You,

Well this is great. Hor.Net has definitely evolved. Im learning assembly and might use this as a kernel for my OS (:

And will advertise it in the OS official trailer
Right Now I have a Concept trailer tho
Concept Trailer: https://www.youtube.com/watch?v=4H3W8HIGI5U

Core

**Comment by laurinyev** [comment]
nice, thank you
and the concept trailer looks awesome.
I will develop h0r.net to the point that it can load modules by the end of the summer If I don't,
 you can always fork it :)
lolguy91 , the kernel guy
EDIT: I made a promotion video for you(I hope you don't mind that I edited an image of one of your discord messages for the thumbnail):
https://www.youtube.com/watch?v=nKTRDsq-CXs
